### ISSUE TITLE
Querying StreamSet data returns a 400 error

### ISSUE THREAD

**Issue by rodp82** [osimloeff/PI-Web-API-Client-Angular#2]
When querying for a streamSet, I'm getting the following error:
"Cache-Control header may not be specified on bulk data requests."

```
this.webApiService.streamSet.getInterpolated(webId).subscribe(res => {
    console.log(res);
  }, error => {
    console.log(error.json());
})
```

I know it's possible to disable the check for cache control headers in the web API runtime configuration ([see docs](https://livelibrary.osisoft.com/LiveLibrary/content/en/web-api-v9/GUID-B7168067-94C5-4E99-96B7-6098B9501261)), but I'd prefer not to do that.

How can I make sure the cache control headers aren't being sent?
Looking in chrome dev tools, I don't see cache control headers being sent

![image](https://user-images.githubusercontent.com/1509474/43383989-388b1e72-940f-11e8-93dc-154d02c2d55e.png)

**Comment by osimloeff** [comment]
Hello Rod,

I am using the code below against PI Web API 2018 and it works fine:

    this.piWebApiHttpService.streamSet.getInterpolated(piElementWebId).subscribe(res => {
        console.log(res);
      }, error => {
        console.log(error.json());
    });

What is the version of your PI Web API? I would try to upgrade if it is not 2018. 

Finally, if you update to 1.11.3, you will be able to define the cache header on the 5th input of the client constructor:

 this.piWebApiHttpService.configureInstance('https:/marc-web-sql.marc.net/piwebapi', true, null, null, 'no-cache');

Hope this helps!

**Comment by rodp82** [comment]
Thanks for the quick response, will update to the latest version.
We are using 2017 R2, so will see if I can get it upgraded as well.
